// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE0oV3dXZOF1jNJ0LpgTNmxjxZNRdKtmM',
    appId: '1:946283056416:web:0947e922e0e7f689111b45',
    messagingSenderId: '946283056416',
    projectId: 'seyahat-app-719ff',
    authDomain: 'seyahat-app-719ff.firebaseapp.com',
    storageBucket: 'seyahat-app-719ff.firebasestorage.app',
    measurementId: 'G-4X1F4N9ZK3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnSFfEPnpkhbgYHejjRt9LKZIEPJxSwk',
    appId: '1:946283056416:ios:6e82250816d379d4111b45',
    messagingSenderId: '946283056416',
    projectId: 'seyahat-app-719ff',
    storageBucket: 'seyahat-app-719ff.firebasestorage.app',
    iosBundleId: 'com.example.seyahatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnSFfEPnpkhbgYHejjRt9LKZIEPJxSwk',
    appId: '1:946283056416:ios:6e82250816d379d4111b45',
    messagingSenderId: '946283056416',
    projectId: 'seyahat-app-719ff',
    storageBucket: 'seyahat-app-719ff.firebasestorage.app',
    iosBundleId: 'com.example.seyahatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE0oV3dXZOF1jNJ0LpgTNmxjxZNRdKtmM',
    appId: '1:946283056416:web:bf9a0435eeaf42ff111b45',
    messagingSenderId: '946283056416',
    projectId: 'seyahat-app-719ff',
    authDomain: 'seyahat-app-719ff.firebaseapp.com',
    storageBucket: 'seyahat-app-719ff.firebasestorage.app',
    measurementId: 'G-3ZM725YE6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcyrAQ_AU36xjFsifM_dzqG7Eez7qRoSU',
    appId: '1:946283056416:android:b728ff5b7a7557f9111b45',
    messagingSenderId: '946283056416',
    projectId: 'seyahat-app-719ff',
    storageBucket: 'seyahat-app-719ff.firebasestorage.app',
  );

}